"""Test table

Revision ID: 03631835ca3b
Revises: dcfb92c58072
Create Date: 2021-05-18 17:32:46.110175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03631835ca3b'
down_revision = 'dcfb92c58072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Test',
    sa.Column('TestID', sa.Integer(), nullable=False),
    sa.Column('QuestionNo', sa.Integer(), nullable=False),
    sa.Column('Question_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Question_ID'], ['TestQuestion.QuestionID'], ),
    sa.PrimaryKeyConstraint('TestID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Test')
    # ### end Alembic commands ###
