"""UserAnswer table

Revision ID: bfcf4bd01a35
Revises: 481b1e903226
Create Date: 2021-05-18 18:44:18.518323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcf4bd01a35'
down_revision = '481b1e903226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Test', sa.Column('User_Input', sa.Float(), nullable=True))
    op.add_column('user_answers', sa.Column('Test_ID', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_answers', 'Test_ID')
    op.drop_column('Test', 'User_Input')
    # ### end Alembic commands ###
