"""TestQuestions table

Revision ID: dcfb92c58072
Revises: e644fce9197f
Create Date: 2021-05-18 17:26:59.278164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcfb92c58072'
down_revision = 'e644fce9197f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TestQuestion',
    sa.Column('QuestionID', sa.Integer(), nullable=False),
    sa.Column('Question', sa.Text(), nullable=True),
    sa.Column('Answer', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('QuestionID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TestQuestion')
    # ### end Alembic commands ###
