"""QuizAnswers table

Revision ID: e644fce9197f
Revises: 588b003393d6
Create Date: 2021-05-17 15:37:59.840398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e644fce9197f'
down_revision = '588b003393d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mimeType', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('img')
    )
    op.create_table('quiz_answers',
    sa.Column('QuizID', sa.Integer(), nullable=False),
    sa.Column('Module', sa.Text(), nullable=True),
    sa.Column('QuizText', sa.Text(), nullable=True),
    sa.Column('QuizAnswer', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('QuizID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_answers')
    op.drop_table('img')
    # ### end Alembic commands ###
