"""TestQuestion Table

Revision ID: f1c57da3f12c
Revises: fd99636c0989
Create Date: 2021-05-19 14:12:29.059724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c57da3f12c'
down_revision = 'fd99636c0989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TestQuestion', sa.Column('Answerkey', sa.Text(), nullable=True))
    op.drop_column('TestQuestion', 'Answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TestQuestion', sa.Column('Answer', sa.FLOAT(), nullable=True))
    op.drop_column('TestQuestion', 'Answerkey')
    # ### end Alembic commands ###
