"""TestQuestion Table

Revision ID: fd99636c0989
Revises: be5692d828e0
Create Date: 2021-05-19 14:04:30.771543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd99636c0989'
down_revision = 'be5692d828e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TestQuestion', sa.Column('QuestionText', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TestQuestion', 'QuestionText')
    # ### end Alembic commands ###
